# Generated by Django 5.2 on 2025-04-16 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Tahrirlandi'), ('delete', "O'chirildi"), ('in', 'Kirim'), ('out', 'Chiqim')], max_length=10)),
                ('object_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='icecream',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='icecream',
            constraint=models.UniqueConstraint(fields=('code', 'name', 'camera'), name='unique_ice_combination'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
